version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_pokemon
    environment:
      POSTGRES_USER: pokemon_user
      POSTGRES_PASSWORD: pokemon_pass
      POSTGRES_DB: pokemon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
