services:
  postgres:
    image: postgres:15
    container_name: postgres_pokemon
    environment:
      POSTGRES_USER: pokemon_user
      POSTGRES_PASSWORD: pokemon_pass
      POSTGRES_DB: pokemon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: pokemon_app
    depends_on:
      - postgres
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/chave_teste_dev.json
      POSTGRES_HOST: postgres
      POSTGRES_DB: pokemon_db
      POSTGRES_USER: pokemon_user
      POSTGRES_PASSWORD: pokemon_pass
    volumes:
      - ./app:/app
    command: ["python", "main.py"]
    restart: always

  dashboard:
    build: .
    container_name: pokemon_dashboard
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: pokemon_db
      POSTGRES_USER: pokemon_user
      POSTGRES_PASSWORD: pokemon_pass
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
    volumes:
      - ./app:/app
    restart: always

volumes:
  postgres_data:
